### ISSUE TITLE
How can I use events?

### ISSUE THREAD

**Issue by Mojtaba-Reyhani** [stefangabos/Zebra_Accordion#3]
If I want to add a div with special font awesome character (like fa-chevron-down) after box title when collapsed (Closed, collapsed state) and remove that character and replace it with new character (like fa-chevron-up) as box title when expended(opened state) add some functionality like [jQuery Accordion](https://vctrfrnndz.github.io/jquery-accordion/).
I try below code but it seems that something is wrong:
```
$('.Zebra_Accordion').on('onOpen', function(e) {
      $(this).append( "<span class='fa fa-chevron-down'></span>" );
  });

$('.Zebra_Accordion').off('onClose', function(e) {
      $(this).append( "<span class='fa fa-chevron-up'></span>" );
  });
```
I'm beginner and not an expert, So please try to give a detailed answer or any reference as I don't know anything about your plugins events and some other expressions.
Thanks

**Comment by justcurious** [comment]
Answered here https://stackoverflow.com/a/46250100/1544886
