### ISSUE TITLE
How can I customize zebra accordion to when I click on open box it's become close?

### ISSUE THREAD

**Issue by Mojtaba-Reyhani** [stefangabos/Zebra_Accordion#5]
How can I customize `zebra accordion` to when I click on the open box (open content, open menu) then it becomes close?
Is there any option or is it possible in `collapsible: false` situation when I click on open menu then it becomes close, just like [ jQuery Accordion](https://vctrfrnndz.github.io/jquery-accordion/) in `Accordion Group (single open)` situation?

**Comment by stefangabos** [comment]
That's exactly what happens if you set `collapsible: true`

**Comment by Mojtaba-Reyhani** [comment]
Thanks for the response, but when I set `collapsible: true` more than one menu can be open at the same time.

**Comment by stefangabos** [comment]
ok, will fix it

**Comment by Mojtaba-Reyhani** [comment]
Thank you so much.

**Comment by Mojtaba-Reyhani** [comment]
Thank you so much.

**Comment by stefangabos** [comment]
This should now be fixed by 6fc3ed9

**Comment by Mojtaba-Reyhani** [comment]
Thank you so much for your effort and responsibility, I appreciate you a lot.
